apiVersion: v1
kind: Service
metadata:
  name: ngxd-hello-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: ngxd-hello
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30002
