apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
spec:
  replicas: 2
  selector:
    matchLabels:
      name: site-ngxd-hello
  template:
    metadata:
      labels:
        name: site-ngxd-hello
    spec:
      containers:
        - name: ngxd-hello
          image: nginxdemos/hello
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: web
              path: /
---
apiVersion: v1
kind: Service
metadata:
  name: site-nginx-hello-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: site-ngxd-hello
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-nginx-ingress
  annotations:
    #app.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ngxd-hello.brulenet.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: site-nginx-hello-service
              port:
                number: 80