apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngxd-hello
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngxd-hello
  template:
    metadata:
      labels:
        app: ngxd-hello
    spec:
      containers:
        - name: ngxd-hello
          image: nginxdemos/hello
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP
          readinessProbe:
            httpGet:
              port: web
              path: /
      topologySpreadConstraint:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ngxd-hello
